language: rust

stages:
  - test
  - "Advanced Tests"
  - "Other"

matrix:
  fast_finish: true
  include:
    - stage: test
      name: stable
      env: CACHE_JOB=stable
      rust: stable
      script:
        - cargo test
    - stage: test
      name: beta
      env: CACHE_JOB=beta
      rust: beta
      script:
        - cargo test
    - stage: test
      name: rustfmt
      env: CACHE_JOB=stable
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - stage: test
      name: clippy
      env: CACHE_JOB=stable
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy
    - stage: "Advanced Tests"
      name: nightly
      env: CACHE_JOB=nightly
      rust: nightly
      script:
        - cargo test
    - stage: "Advanced Tests"
      name: hocon_test_suite
      env: CACHE_JOB=stable
      rust: stable
      script:
        - ./hocon-test-suite.sh
    - stage: "Other"
      name: "no default features"
      rust: stable
      os: linux
      env: CACHE_JOB=no-default
      script:
        - cargo test --no-default-features

cache:
  - cargo
  - timeout: 1000

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
