[package]
name = "hocon"
version = "0.2.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2018"
description = "Reads HOCON configuration files"
repository = "https://github.com/mockersf/hocon.rs"
homepage = "https://github.com/mockersf/hocon.rs"
documentation = "https://docs.rs/hocon.rs"
keywords = ["hocon", "configuration"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "mockersf/hocon.rs" }

[dependencies]
nom = "4.2"
serde = { version = "1.0", optional = true }
java-properties = "1.1"

[dev-dependencies]
test-generator = "0.2"
insta = "0.6"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

[features]
default = [ "test-snapshot", "serde-support" ]
test-snapshot = []
serde-support = [ "serde" ]
